### ISSUE TITLE
Paths for Wireshark, Text Editor and PDF reader don't survive program exit / restart.

### ISSUE THREAD

**Issue by delysis** [iadgov/GRASSMARLIN#1]
Paths for Wireshark, Text Editor and PDF reader don't survive program exit / restart.

Second issue: there is no browsing to get the path to "Preferred text editor" or "Preferred text editor."  (See "Set" when what we want is "Find," as with the Wireshark path field).  Also, the word "Find" is typically reserved for search-like functionality, whereas "Browse..." is the most idiomatic label for the functionality the "Find" button provides.

![image](https://cloud.githubusercontent.com/assets/7828802/12766143/319b70c8-c9d0-11e5-90fa-4c40add34288.png)

**Comment by iadgovuser4** [comment]
Thank you very much for downloading and providing feedback. We are looking at the issue internally and will provide a status update as soon as possible.

**Comment by iadgovuser1** [comment]
Is this still an issue with the latest release (version 3.2)?

**Comment by iadgovuser5** [comment]
This issue has been resolved in version 3.2.
