### ISSUE TITLE
jnwizard build-impl.xml missing

### ISSUE THREAD

**Issue by slimm609** [iadgov/GRASSMARLIN#2]
the build.xml for JNWizard trys to import build-impl.xml but the build-impl.xml was not included with the source. 

Thanks

**Comment by slimm609** [comment]
any update on build-impl for jnwizard?

**Comment by iadgovuser4** [comment]
Our apologies for the delay. The build-impl.xml is an artifact from the NetBeans build and we should have removed that. You can ignore those xml build artifacts and leverage the IDE of your choice to compile.
