### ISSUE TITLE
Installation for linux OS ?

### ISSUE THREAD

**Issue by darklink64** [iadgov/GRASSMARLIN#3]
Thanks for the great tool ! I find it very useful on Windows. 

On the other hand, on Linux, I have some troubles installing it. In fact, after downloading the source file, I can't compile and install the program. There's no "configure.ac" or "configure.in" files and a "make" command or "./configure" doesn't work.

I eventually run an autogen.sh script and it says that : "the GNU Build System is at least not used in this directory" (I was in the directory of the Grassmarlin source file) implying that it's not compatible with GNU System.

The guide says that grassmarlin is available on some version of linux but i can't seem to find a way to install it. Do you have a solution to this ? (I've experimented installation on ubuntu 14.04)

(sorry if my expression is bad, english is not my native language)

**Comment by iadgovuser1** [comment]
Try the Linux installers for the latest release: https://github.com/iadgov/GRASSMARLIN/releases/latest aka https://github.com/iadgov/GRASSMARLIN/releases/tag/v3.2.0
