### ISSUE TITLE
Updated hashes?

### ISSUE THREAD

**Issue by bwiese** [iadgov/GRASSMARLIN#9]
There is probably a better way to communicate this, but I couldn't find it.

Just downloaded the Windows Full x64 and MSI versions however the hashes do not match.
It looks like the hash db page needs to be updated?
https://github.com/iadgov/GRASSMARLIN/blob/master/FileHash.md

**Comment by iadgovuser5** [comment]
Once I distribute the Linux Installers, I plan on updating the file hashes.

**Comment by iadgovuser5** [comment]
The new installers have been uploaded with the new file hashes.

**Comment by iadgovuser22** [comment]
Due to the lack of activity on this issue, I'll consider it resolved.
Closing the issue. Oct 13, 2017
